---
- hosts: 172.31.88.189
  become: yes
  tasks:
  - name: i want excute linux commands 
    command: hostname -f
    register: myfirstvaribleresult

  - name: i want to display first task results
    debug:
      msg: "{{myfirstvaribleresult}}"
    
