---
- hosts: 172.31.88.189
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy my static file
    copy:
      src: mytestfile
      dest: /home/ubuntu/mystaticfile
  - name: install webserver
    apt: 
      name: apache2
      state: present 

  - name: copy dynamic files
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
      
  - name: download internet files
    get_url:
      url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes